### ISSUE TITLE
Remove Obsolete-Attribute for synchronous methods

### ISSUE THREAD

**Issue by danielmue** [jefffhaynes/BinarySerializer#100]
The async/await pattern does make sense for IO bound operations. The often used ```MemoryStream``` does not provide any kind of true asynchronous implementation[0]. All methods perform the operation synchronously and return an already completed Task. Keeping this in mind lets me reason that using the synchronous ```Read(..)``` method will be faster than setting up an asynchronous operation.

After reading [1] I am not really sure if using the asynchronous API gives us ANY performance improvement at all (if you do not use some kind of buffered stream).

> Jon: The reason that the BinaryReader/Writer do not have XxxAsync methods is that the methods on those types typically read/write **only very few bytes** from an underlying stream that has been previously opened. In practice, the data is frequently cached and the time required to fetch the data from the underlying source is typically so small that it is not worth it doing it asynchronously.
> [..]
> **In general, you should only consider Async IO methods if the amount of data you are reading is significant (at least several hundreds or thousands of bytes)**, or if you are accessing a resource for the first time (e.g. a first read from a file may require to spin up the disk even if you are reading one byte).

Furthermore I should mention that a lot of methods in BinarySerializer don't use ```.ConfigureAwait(false)``` which leads to continues context switches and a danger of deadlocks in UI code [3]. 

[0] https://referencesource.microsoft.com/#mscorlib/system/io/memorystream.cs,2142088b3533a169,references
[1] https://blogs.msdn.microsoft.com/pfxteam/2012/03/24/should-i-expose-asynchronous-wrappers-for-synchronous-methods/
[2] https://msdn.microsoft.com/en-us/magazine/jj991977.aspx
[3] https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f

**Comment by jefffhaynes** [comment]
One of the main reasons I implemented async methods is that not many blocking non-async operations are easily cancellable. This is especially true in serial controllers and the like. In those cases it’s not really about performance (which can be worse) but about better thread management. Similarly it can make thread management easier in cases where serialization is taking place in the UI thread so that naturally async operations don’t block the UI.

Ultimately I don’t know that I think the non-async methods have a lot of utility. But I realize they are still popular and will probably remain so.

—
If you want to build a ship, don't drum up people to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.

Antoine de Saint-Exupery
________________________________

**Comment by jefffhaynes** [comment]
Oh, also the async methods are absolutely not wrappers. The async-ness of the methods is maintained all the way through the stack and down to the stream, at a cost of great complexity.

—
If you want to build a ship, don't drum up people to collect wood and don't assign them tasks and work, but rather teach them to long for the endless immensity of the sea.

Antoine de Saint-Exupery
________________________________

**Comment by jefffhaynes** [comment]
Removed obsolete markings
