### ISSUE TITLE
Bug: SubtypeDefault/ItemSubtypeDefault Doesn't Support Types Inheriting IBinarySerializable

### ISSUE THREAD

**Issue by Texnomic** [jefffhaynes/BinarySerializer#139]
When using Interface-based Abstractions, SubtypeDefault Attribute is perfect for such case. 

The following case works **only if** type `Domain` is using standard serialization, while it **fails silently** if type `Domain` is using custom serialization by implementing `IBinarySerializable`.

```csharp
public class Question : IQuestion
{
        [FieldOrder(0)]
        [SubtypeDefault(typeof(Domain))]
        public IDomain Domain { get; set; }
}
```
To workaround this issue, we need to create a fake `DomainFactory` in order to use `SubtypeFactory` which supports custom serialization by implementing `IBinarySerializable`.

```csharp
public class DomainFactory : ISubtypeFactory
{
        public bool TryGetKey(Type ValueType, out object Key)
        {
            throw new NotImplementedException();
        }

        public bool TryGetType(object Key, out Type Type)
        {
            Type = typeof(Domain);
            return true;
        }
 }

public class Question : IQuestion
{
        [FieldOrder(0)]
        [SubtypeFactory(nameof(Domain), typeof(DomainFactory), BindingMode = BindingMode.OneWayToSource)]
        public IDomain Domain { get; set; }
}
```

**Comment by jefffhaynes** [comment]
I thought I had a solution for this but the more I think about the less I understand it.

If you're serializing the Question class and Domain is null, then the correct behavior is to treat that value as null, not to fallback to something else.  If you're deserializing, then it does make sense to resolve that type because you're not in control of the data.

In your use case, why not simply set Domain to Domain during serialization?
