### ISSUE TITLE
SerializeAs for collections

### ISSUE THREAD

**Issue by nullpainter** [jefffhaynes/BinarySerializer#175]
Related to #174 , my use case involves padded strings, and critically that no null values are serialized. The approach of using `SerializeAs` with the new `PaddingValue` works well for strings, however not for string collections.

With this:

```c#
public class TestClass
{
  [FieldOrder(2), FieldCount(2), ItemLength(5)]
  [SerializeAs(SerializedType.SizedString, PaddingValue = 0x20)]
  public List<string> TestProperty { get; set; }
}
```

And initialisation with:

```c#
 var testObject = new TestClass
 {
  TestProperty = new List<string>
  {
    "one", "two"
  }
};
```
the resultant serialized bytes are:

```
6F 6E 65 00 00 74 77 6F 00 00                   	one..two..
```

Unless I've missed something in the documentation, this almost sounds like a new attribute may be required (`SerializeItemsAs` or equivalent?)

**Comment by jefffhaynes** [comment]
Yeah, I think this is a use case that I've mostly been ignoring :).  Let me see what it would take.

**Comment by jefffhaynes** [comment]
I think what I'm leaning towards is simply inheriting the SerializeAs settings from the parent collection.  That's currently how encoding and endianness is handled.  I think it works because those properties wouldn't make sense at a collection-level so there's no need to have item-specific properties (vs something like length where it would be confusing).
