### ISSUE TITLE
Fails to Serialize when field type is Dictionary or Implements [IDictionary]

### ISSUE THREAD

**Issue by jwxNobody** [jefffhaynes/BinarySerializer#188]
Are there any plans to add support for Dictionaries?

`
public Dictionary<string, object> Items { get; set; }
`

Exception occurs when attempt to serialize: {"Cannot serialize objects that implement IDictionary."}

**Comment by jefffhaynes** [comment]
A dictionary doesn't really have meaning in the context of serialization since it represents a way of looking something up. If you are looking to serialize a list of key/value pairs, then I recommend just doing that as it will allow you to control the serialization of the pairs rather than me guessing how they should be serialized. 

Alternatively, if you don't care how it gets serialized, this is probably the wrong library and I would recommend using something like protobuf or json.
