### ISSUE TITLE
Is there a way to map a range of values to a subtype?

### ISSUE THREAD

**Issue by lamesjinden** [jefffhaynes/BinarySerializer#59]
Hey,

*deserialization only*

I'm utilizing the SubType attribute, bound to a "Messge ID" field. I'd like to map a range of consecutive values to a specific subtype Type - I think I would also need to specify BindingMode = OneWay. I could, in my case, create 256 individual SubType attributes to accomodate this range, but I'd prefer not to. I tried a few arrangements around FieldValueAttribute with a ConverterType specified which result in an exception due to forward binding not being supported. 

Any thoughts?

I can provide code examples if necessary. 

Thanks,
-james

**Comment by jefffhaynes** [comment]
Interesting...let me think about it. I assume the DefaultSubtypeAttribute isn't really appropriate?

---------------
I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses - Johannes Kepler




On Mon, Feb 27, 2017 at 4:42 PM -0500, "james" <notifications@github.com> wrote:












Hey,


deserialization only


I'm utilizing the SubType attribute, bound to a "Messge ID" field. I'd like to map a range of consecutive values to a specific subtype Type - I think I would also need to specify BindingMode = OneWay. I could, in my case, create 256 individual SubType attributes to accomodate this range, but I'd prefer not to. I tried a few arrangements around FieldValueAttribute with a ConverterType specified which result in an exception due to forward binding not being supported.


Any thoughts?


I can provide code examples if necessary.


Thanks,

-james

**Comment by jefffhaynes** [comment]
Wait, why doesn't Subtype with a converter work?

---------------
I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses - Johannes Kepler
_____________________________

**Comment by lamesjinden** [comment]
It does. Amazing. Thanks.

**Comment by jefffhaynes** [comment]
Awesome 

---------------
I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses - Johannes Kepler




On Mon, Feb 27, 2017 at 7:42 PM -0500, "james" <notifications@github.com> wrote:












It does. Amazing. Thanks.
