### ISSUE TITLE
feature request: how about extending this to read and write EXI

### ISSUE THREAD

**Issue by ericleigh007** [jefffhaynes/BinarySerializer#6]
Just a feature request, but it would be cool to get your thoughts.

-thanks
-e

**Comment by jefffhaynes** [comment]
Thanks for the feedback. While not intimately familiar with EXI, my guess is that it would be fairly straightforward to develop an EXI library based on this one. However, my intention with BinarySerializer is to simply allow the format declaration rather than dictate or suggest the nature of it. I feel like EXI is a layer up and probably belongs in it's own project. 

Thanks,

Jeff
