### ISSUE TITLE
TimeSpan and DateTime Support

### ISSUE THREAD

**Issue by serkanayaz** [jefffhaynes/BinarySerializer#75]
Hi,

Can you support TimeSpan and DateTime types?

Best regards

public class DummyClass
 {
        [FieldOrder(0)]
        public TimeSpan Duration { get; set; }
        [FieldOrder(1)]
        public DateTime Date { get; set; }
    }

**Comment by jefffhaynes** [comment]
The problem is that while I could support it, there’s no standard way of serializing either type so inevitably anything I put in would solve one particular case but likely not others.

Could you simply create your own time classes that define the structure you need?  You could always add methods or ignored properties that translate to and from DateTime or TimeSpan. This is typically how I’ve solved this problem in the past when using the serializer with date/time structures.

________________________________

**Comment by serkanayaz** [comment]
The converter class for TimeSpan is below. How can I implement as a Long type to BinarySerializer?

public class TimeSpanConverter
    {
        public long Convert(TimeSpan timeSpan)
        {
            return timeSpan.Ticks;
        }

        public TimeSpan Convert(long ticks)
        {
            return new TimeSpan(ticks);
        }
    }

**Comment by jefffhaynes** [comment]
I wouldn't use a converter.  I would simply create a class with a convenience property.

```c#
public class MyTimeSpan
{
    public long Value { get; set; }

    [Ignore]
    public TimeSpan TimeSpan
    {
        get => TimeSpan.FromTicks(Value);
        set => Value = value.Ticks;
    }
}
```

**Comment by serkanayaz** [comment]
Simply and nice resolve. Thank you. I can use that. How can I do with a converter?
