### ISSUE TITLE
Why are the sync methods now obsolete

### ISSUE THREAD

**Issue by andyvans** [jefffhaynes/BinarySerializer#86]
Hi Jeff

First off, this is a great library you have here. Very useful.  

In the new async code support you have added, I see you have marked the non-async methods obsolete.  I understand that on large/slow streams there are advantages to using async methods, but are you planning on removing the non-async methods.  Particularly, there doesn't seem to be any reason to make the following methods obsolete:

public T Deserialize<T>(byte[] data, object context = null)
public object Deserialize(byte[] data, Type type, object context = null)

Is there any advantage to using async methods when the serialized data is sourced from a byte array?

Cheers
Andy

**Comment by jefffhaynes** [comment]
Thanks. No, there may be no advantage. However, in other cases there is a significant advantage if you have to worry about timeouts or cancellations. The only reason I’m considering removing the sync methods eventually is because maintaining both stacks is tricky.  Unfortunately there are basically unique pipelines all the way down to the read and write methods, which may have different async vs sync semantics so there’s a lot of code duplication.

Obviously you can run the async methods synchronously but I get that it’s not ideal. Regardless, it may be awhile before I remove the sync methods, if ever.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by andyvans** [comment]
I saw the changes and agree two implementations is tricky. And you are probably also reluctant to add Task.Run wrappers around the the async functions in the non-async methods. Thanks for the update.
